"""add secret_name column

Revision ID: ab6f00c50ec7
Revises: 9930fc30b329
Create Date: 2026-09-09 22:14:22.396637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # required: autogenerate renders sqlmodel.sql.sqltypes.AutoString()
                 # for str columns but never adds this import itself (verified bug/gap)


# revision identifiers, used by Alembic.
revision: str = 'ab6f00c50ec7'
down_revision: Union[str, Sequence[str], None] = '9930fc30b329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('secret_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hero', 'secret_name')
    # ### end Alembic commands ###
